### PR TITLE
Fix linting for mdl, add additional linters, fix TravisCI

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by woubuc** [comment]
@grimreaper if you check `travis.yml` it just runs `htmlhint`, `csslint` and `jshint` directly, it doesn't go through the scripts in `ci/`. So it should already run jshint.

**Comment by grimreaper** [comment]
@woubuc ah, thanks for the hint. Fixed.

**Comment by woubuc** [comment]
Nothing's broken afaik? I changed `travis.yml` to use the node tools instead of the old python + java solution. Since they're just a single command for each test, I just declared those in `travis.yml` directly.

**Comment by grimreaper** [comment]
@woubuc it broke the use of the ci scripts, it puts shell scripts in a yaml file, it caused mdl and html5validate to not run.

**Comment by woubuc** [comment]
@grimreaper html5validate doesn't have to run anymore, I replaced it with htmlhint. Wouldn't it be easier to just add a Node-based markdown linter to `travis.yml` since that's all that you seem to be missing?

**Comment by grimreaper** [comment]
I'm trying to figure out what happened to the rest of the changes in #41.
Also, we should revert the changes that caused .travis.yml to have a shell script instead of running an external script.
Looking at htmlhint now to see if html5validate is is actually replaced.

**Comment by woubuc** [comment]
Huh, you're right, there does seem to be something missing between that one and #33 (which was merged in later than #41). I'm going to have to check the commit history to see where that went wrong.

In any case, I propose for now you add a Node markdown validator instead of reverting it all back to the Java solution (which imo isn't a good way to move forward and it makes it difficult for people to test locally before they commit).

As for the rules that htmlhint uses, they can be configured in `.htmlhintrc` and that's definitely open for discussion, I just put what I thought would provide a good guideline without being too strict.

**Comment by grimreaper** [comment]
>  I propose for now you add a Node markdown validator instead of reverting it all back to the Java solution
The Java validator is for HTML5, not node. It does not appear that htmlhint can be configured to correctly validate HTML5 though I'm not sure a human is likely to write HTML which is unparsable.

Can you point me to a node solution for for mdl or HTML?

**Comment by woubuc** [comment]
In my experience htmlhint works just fine, depending on the configuration in `.htmlhintrc`. Can you give an example of something it doesn't validate correctly?

For markdown https://github.com/wooorm/remark-lint looks promising.

**Comment by grimreaper** [comment]
I have some things going on, but I'll look into those options in a bit.

**Pull request merged**
