### PR TITLE
List pull requests in index, allow for +1'ing + added link to hosted version in readme.md

### PR DESCRIPTION
**Pull request by frattaro**
Used the [GitHub API](https://developer.github.com/v3/pulls/#list-pull-requests) to call pull requests, lists them on index.html with [jQuery](https://jquery.com/) and [Mustache](https://github.com/janl/mustache.js/) from [cdnjs.com](https://cdnjs.com/). Adds a [Google +1 button](https://developers.google.com/+/web/+1button/) to each pull request.

Learned Markdown and tested changes with [dillinger.io](http://dillinger.io/)

Having never used github.com as a repository - forked, committed, sync'd, and pull requested without using the command line. [Thanks to this blog post.](http://rickrainey.com/2013/07/27/visual-studio-and-gitub-the-basics-of-working-with-existing-repositories-2/)

### CODE REVIEW

**Comment by frattaro** [comment]
Added github pages, so accessible now at [https://frattaro.github.io/1pr](https://frattaro.github.io/1pr)

**Comment by DominicBisset** [comment]
I really like the idea of listing the pull requests, but I'm less keen on Google plus integration.  Not everyone uses it (dev.to itself uses GitHub and Twitter sign-in so maybe those would be more appropriate for the audience; its a shame GitHub doesn't have a method to vote directly on PRs).  Also on the general philosophy of this I think we should try to keep PRs as focused as possible.  So the pull request list should be separate from any voting on those in my view, regardless of the specific tech.

All of this is said knowing I have no authority on this project as a random outsider.  So do what you like really.

**Comment by frattaro** [comment]
@DominicBisset At first, I thought a voting feature, which is prohibited by Facebook's terms of service for the Like buttons (but isn't for G+), and then I thought - this isn't a democracy anyway, it's a dictatorship so maybe it's not violating. But by then I had already done it, so I just worded it as look at others' contributions with an interactive appreciation mechanism. Simply listing the pull requests alone seems redundant to the project pages. Maybe a star count/starring the fork repo would be a suitable replacement.

I honestly just wanted a link to the github.io version in the readme.md - it'll keep me more engaged if I have an easy way to see the current output.

**Comment by DominicBisset** [comment]
@frattaro I'd still disagree with Facebook Like buttons on similar grounds as it happens. As you rightly point out its a dictatorship so my views count for naught.

I've been pondering integrating Firebase as it would serve as a pseudo-database with a level of flexibility that suits this project that most cloud databases can't support.  This would get around any ToS issues and be more useful in the future for other persistence needs.

**Comment by frattaro** [comment]
@DominicBisset Adding a database would add a lot of overhead for contributors, but it would definitely be a game-changer. Maybe a flat-file db would work best at first.

I've been thinking "What are our choices for a project without a central db?" and figured either a game or personal productivity application. I branched my repo and made a simple, ugly game (click-masher type) but haven't published it yet. I figured I'd pull request it at some point. But I find it to be a drag to pull changes into a fork...

**Comment by frattaro** [comment]
@DominicBisset 

oh. https://buttons.github.io/

lol

**Comment by dakebl** [comment]
Really great idea! I'm with @DominicBisset on the social intergrations though. I think the PR's and the conversion feeds (such as this one) should speak for themselves. You might consider adding the pull requests feature to their own page and adding it to the header navigation, as I think it's a feature in it's own right :)

**Comment by DominicBisset** [comment]
@frattaro 
> "But I find it to be a drag to pull changes into a fork..."

I agree with you there.  I think this is going to quickly become an impenitrable tangle if everyone is trying to reference everyone else.

And with regard to the GitHub buttons project, they're close but you still cant star PRs so it wouldn't work as a voting mechanism.

**Comment by frattaro** [comment]
Just merged the latest. It was a lot easier, thepracticaldev/master started showing up in my list of remote repos for whatever reason (in Visual Studio).

@DominicBisset  I thought the fork repo starring would work but people will re-use repos.

@dakebl I didn't make a second page because I didn't want to throw Backbone into my already opinionated PR. I only feel OK as is because it's under 30 lines of non-lib JS.

**Comment by frattaro** [comment]
tabs are too frustrating to work with. withdrawing this PR.

**Comment by woubuc** [comment]
@frattaro what is it that bothers you about tabs?

**Comment by frattaro** [comment]
@woubuc 
In Visual Studio (up to and including) 2015, tabs/spaces aren't solution-based settings, it's language-based, so if I work on something else I need to switch all the global settings back and forth.

Visual Studio 2017 became available earlier this month, and it supports something called .editorconfig, so tonight (eastern US time) I'll install it and see what's new.

I didn't think it was a big deal pulling this request since it can be done in 3 lines of JS, a handful of html elements and 2 CSS rules. The important thing is that link to the github.io page got into the readme.md

**Comment by woubuc** [comment]
@frattaro It's not a big deal per se, I was mostly wondering what the problem was that you had with tabs (since I'm the one who introduced the coding standards as they are now).

The `.editorconfig` file that was merged in with the last PR solves your exact problem by setting the formatting settings on a per-project basis, independently from your IDE settings (and it stores the config in a file so that it can be tracked in version control). That way, your IDE will (or at least, should) switch to the correct settings when working on a specific project, but leave your settings for other projects untouched.

I'd recommend you check out http://editorconfig.org to learn a bit about what it does, cause it's a really useful tool when you're working on different projects with different coding standards.

Also according to the site there are plugins that enable `.editorconfig` support for both VS and VS code. But all the better if VS 2017 has built-in support, of course 😄

**Pull request closed without merging**
