### PR TITLE
Voting for PRs via Google+ Buttons - and a video game.

### PR DESCRIPTION
**Pull request by frattaro**
Back with VS2017.

https://frattaro.github.io/1pr/

### CODE REVIEW

**Comment by dakebl** [comment]
Very cool. I'd suggest moving the voting to its own page though personally.
The game is cool too. Maybe add some intrusions on how to play?
Also, the game is not mobile friendly

**Comment by dakebl** [comment]
Might be worth separating the voting system and the game into two pull requests as well

**Comment by woubuc** [comment]
I agree with @dakebl that it would be better to have a separate PR for the game. Cool idea though 😄

**Comment by dakebl** [comment]
@frattaro - I raised a PR on your branch for your consideration: https://github.com/frattaro/1pr/pull/1

I saw you had a separate branch with the game in it, so I removed it from the above PR and pointed it at your master branch. I moved the voting section to a separate page while I was there too.

**Comment by frattaro** [comment]
Sorry I couldn't respond sooner, job and family. I hope my changes encourage more pull requests.

**Pull request merged**
