### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by nrobinson2000**

### CODE REVIEW

**Comment by dakebl** [comment]
Might be cool invert the icon for the favicon (black background, white icon).
Would match dev.to's then 😆

**Comment by nrobinson2000** [comment]
I'll try that right now.

**Comment by dakebl** [comment]
Digging it! 👍 
image

**Comment by nrobinson2000** [comment]
Speaking of logos, have you seen the logo for http://firstpr.me/ ?

I do like the simplicity of using the just the octicon pr logo though.

**Comment by dakebl** [comment]
@nrobinson2000 Yeah, quite a cool neat logo they have.
Maybe someone could design a similar style logo for this project?

**Pull request merged**
