### PR TITLE
Added database for storing and sharing data

### PR DESCRIPTION
**Pull request by DominicBisset**
This pull request implements a firebase system, as proposed in issue #29, for saving user data. 

All it does a the moment is facilitate signing in and out (using GitHub accounts, so consistent with the focus this project has taken), admin user privilidges, and managing data migrations.  In other words it doesn't do anything that end-users will actually appreciate, but it is a platform for other people to build on. 

For example:
- Port the google-plus based PR voting to inhouse voting that records better who voted for what and when
- Implement a high score table for the game that has been built
- Solve issue #38 by periodically calculating the number of actual issues and showing that number rather than the misleading one from the API.

See the README for details on setting up the database.  Hopefully it's self-explanitory.

This is not dependant on any other PRs.

This PR does also include fix 28a1d76 because the site heavily leans on target="_blank" which is a [bad idea](https://dev.to/ben/the-targetblank-vulnerability-by-example).

You can view the changes at dominicbisset.github.io/1pr, but as all you can do is sign in and out (unless I make you an admin) so there's not much to see.

N.B. I'm aware the build fails - it's due to the nesting of the ordered and unordered lists in the README explaination.  Either Travis complains about the indentation being too great or it complains about inconsistent indentation

### CODE REVIEW

**Comment by woubuc** [comment]
Cool! Having a database will give us a lot of possibilities 👍

**Comment by DominicBisset** [comment]
Just realised that the nav is overflowing on narrow screens. It'll be a while before I get a chance to fix it.

**Comment by dakebl** [comment]
@DominicBisset Nice job hooking in Firebase! 
Perhaps consider adding the sign in link to the side bar instead, as the sidebar menu button appears in the top-right nav on mobile devices.

**Comment by DominicBisset** [comment]
Just to keep people in the loop:  I did as you suggested, @dakebl and that worked swimmingly, so thanks.  Then I pulled the latest version of thepracticaldev/1pr and discoverd the changes were more substantial than I realised at a glance.   I'm currently having issues loading the scripts with the new async loader but once I get to the bottom of that I'll update this PR.

Then I'll probably add unit tests, because it's not a straightforward system, but I think do that in a separate PR so that people can start using this.

**Comment by woubuc** [comment]
@DominicBisset if you need any help with the async loader, just give me a shout 😃 

Implementing your script should be no more difficult than just adding your script url to the `window.assets` array (at the bottom of `index.html`).

If your script needs to do something async on pageload, you can use the method `window.registerAsyncScript('your script name here');` which returns a function that you should call when your async function is complete. Simplest example is in `scripts/pr-counter.js`.

**Comment by DominicBisset** [comment]
It works!  The layout is functional on mobile. Travis is happy.

**Comment by DominicBisset** [comment]
@benhalpern, you might already be working on this, but the main site is still pointing at my firebase database, so login fails because I haven't authorised thepracticaldev.github.io as a domain.

**Pull request merged**
