### PR TITLE
Added code validation for html, css and javascript

### PR DESCRIPTION
**Pull request by woubuc**
I added htmlhint, csslint and jshint config files to validate the code. The settings and guidelines I added are documented in the readme, I welcome a discussion if there's anything in there that you don't agree with.

The previous Travis test used a rather slow Java-based solution, which I've replaced entirely with this one. It now completes in about 1 minute (down from 2+ minutes for just the html validation).

It's now also easier for other devs to run the tests on their own machine, I've included instructions on how to do this in the readme.

### CODE REVIEW

**Comment by dakebl** [comment]
Linters are not a bad idea at all. 
Might be worth creating a package.json, then people can just run npm install to get the linters, rather than individually installing them.

Could go with something like this:
```
{
  "name": "1pr",
  "version": "1.0.0",
  "description": "One pull request a day",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/thepracticaldev/1pr.git"
  },
  "devDependencies": {
    "csslint": "^1.0.5",
    "htmlhint": "^0.9.13",
    "jshint": "^2.9.4"
  }
}
```

The next step from there could be to add some [npm scripts](https://docs.npmjs.com/misc/scripts) to run the tests?

Might be worth adding a npm/node.js primer to the advice section of index.html to help those who haven't used it before.

**Comment by woubuc** [comment]
@dakebl I wanted to keep this PR as "open" as possible, meaning it's entirely optional to use Node for this.

I'm working on a Node-specific solution in another branch (I'll create another PR for that when it's done), with a Gulp build script that will also concatenate and minify the assets. That will make things easier for us but could potentially scare off devs who aren't familiar with Node or Gulp. Which is why I started with the approach in this PR.

**Comment by dakebl** [comment]
@woubuc Sounds good to me. Node or not, you can't go wrong with decent build tools 😉

**Comment by woubuc** [comment]
@dakebl see #35

**Comment by woubuc** [comment]
Updated! I've merged the latest changes into my branch and fixed the validation errors in the new scripts.

**Comment by grimreaper** [comment]
This commit broke Travis and the ci scripts. Working on fixing them.

**Comment by woubuc** [comment]
@grimreaper how do you mean 'broke them'? The tests seem to be working fine.

**Pull request merged**
