### PR TITLE
Added PR shield, added Font Awesome and restructured slightly

### PR DESCRIPTION
**Pull request by dakebl**
- I moved the H1 padding to a parent div and I moved the 'last merged pr' section into it.
- I re-added the PR Shield from shields .io (Originally introduced by @nrobinson2000 ) . I styled it to be more prominent on the page.
- I added Font Awesome and replaced the text in the Nav with Icons. This looks better on mobile.
- The footer needs styling for mobile, so I added a media query to remove the footer on small devices until it can be made mobile friendly.
- Updated dev.to link to point at https://dev.to/t/1pr

This has now been merged into https://github.com/thepracticaldev/1pr/pull/23 as well 😄

### CODE REVIEW

**Comment by nrobinson2000** [comment]
I do like this, but could you remove the blue underlining of the badge on hover?

**Comment by dakebl** [comment]
I've removed the pesky underline from the image link now @nrobinson2000 
The color is currently set via a GET request parameter, ``?colorB=brightgreen``, which I can only assume is not getting called quick enough to be rendered sometimes. Not sure what we can do about that one, as the github functionality is built into shields itself. 

We could make our own button and get the number of pull requests via the api, I suppose?

**Comment by nrobinson2000** [comment]
I think consistency is key, and we should have a consistent method for showing the number of pull requests.  If we have to keep the button yellow or make our own button that is fine with me.

**Comment by nrobinson2000** [comment]
@dakebl I'm voting for this pull request to be the next.

**Comment by dakebl** [comment]
Cheers @nrobinson2000 
Indeed, consistent UX is important, so I've removed the green background to this end 😄

**Comment by woubuc** [comment]
These changes are now merged into #23.

**Comment by nrobinson2000** [comment]
I removed the green background color in https://github.com/thepracticaldev/1pr/pull/27 as well and I am working on adding the gitter sidecar.

**Comment by nrobinson2000** [comment]
I don't know how I even got that weird binary file instead of the real JS file.

**Pull request closed without merging**
