### PR TITLE
Add html5 validation

### PR DESCRIPTION
**Pull request by grimreaper**
We should have unit tests because unit tests are good

Note that you should enable TravisCI at https://travis-ci.org/thepracticaldev/1pr

### CODE REVIEW

**Comment by grimreaper** [comment]
Proof it works:
image

**Comment by nrobinson2000** [comment]
Shouldn't there also be a build passing icon on the site?

**Comment by grimreaper** [comment]
added a mark to the README.

**Comment by nrobinson2000** [comment]
I personally think the mark should be at the top of the README.

**Comment by grimreaper** [comment]
done

**Pull request merged**
