### PR TITLE
Add badges from buttons.github.io in a footer

### PR DESCRIPTION
**Pull request by nrobinson2000**
View my changes live here
https://nrobinson2000.github.io/1pr/

### CODE REVIEW

**Comment by woubuc** [comment]
Just a thought - what if you put them just above the line, and centered?

**Comment by nrobinson2000** [comment]
I centered the icons and changed them to the ones from https://buttons.github.io which load faster and look nicer. however there is still a bit of lag when they load, and once full loaded they shift the page down which doesn't look very nice.

**Comment by nrobinson2000** [comment]
I think I will put the buttons in the footer instead.

**Comment by dakebl** [comment]
I submitted a pull request to add a banner element to house the H1 and shields. 
I also modified the H1 styles, moving the padding to the .banner class.

https://github.com/nrobinson2000/1pr/pull/3

**Comment by woubuc** [comment]
@nrobinson2000 you can put the buttons inside a div with a set height, that way the page won't shift

**Comment by woubuc** [comment]
Does buttons.github.io have a pull request one? I feel like that's the most important one we should have on the page :smile:

**Comment by dakebl** [comment]
I don't think there is @woubuc . Personally, I think the shields.io is a better fit.

**Comment by nrobinson2000** [comment]
@woubuc @dakebl  I put the buttons in a div with a set height in a floating footer.

https://nrobinson2000.github.io/1pr/

**Comment by aaroneiche** [comment]
I like the matching footer to the menu header across the top.

**Comment by nrobinson2000** [comment]
Thanks, I think this should go into the PR @woubuc is working on  I really like what @woubuc is doing with the nav bar and everything else.

**Comment by woubuc** [comment]
Looks awesome this way! @nrobinson2000 would you mind if I merge this into #23 as well? :smiley:

**Comment by nrobinson2000** [comment]
Feel free to merge this @woubuc

**Comment by dakebl** [comment]
Digging the footer @nrobinson2000

**Comment by woubuc** [comment]
@nrobinson2000 Done! I did add a little bit more space between the buttons, [take a look](https://woubuc.github.io/1pr/).

**Comment by nrobinson2000** [comment]
Wow this looks really good.

**Comment by nrobinson2000** [comment]
Shall I close this PR as you have merged it?

**Comment by nrobinson2000** [comment]
I think I will close this.

**Pull request closed without merging**
