### PR TITLE
Add floating navigation bar, links to stuff, prettyprinted and .gitignore

### PR DESCRIPTION
**Pull request by nrobinson2000**
View my changes live here.

https://nrobinson2000.github.io/1pr/

### CODE REVIEW

**Comment by nrobinson2000** [comment]
I probably need to fix the css so it looks better on mobile though.

**Comment by aaroneiche** [comment]
I like it - I think the links in the navbar should should ```target="_blank"``` though, so they don't take you away from what you're currently looking at.

**Comment by nrobinson2000** [comment]
Done

**Comment by nrobinson2000** [comment]
I've noticed that on mobile I have to tap on the links twice to get them to open.  I think this has to do with `:hover` in the css.  I think I should make the nav bar more mobile friendly before this pr is merged.

**Comment by benhalpern** [comment]
This looks great, and looks like it will be the front-runner for tomorrow. One note: We typically spell dev.to in all lowercase. But I really love this.

**Comment by nrobinson2000** [comment]
@benhalpern I just changed it to lowercase dev.to

**Comment by woubuc** [comment]
Why not use the more semantic `<nav>` element instead of `<ul>` for the navigation?

**Comment by nrobinson2000** [comment]
I changed the `ul` to `nav`.

**Comment by nrobinson2000** [comment]
@woubuc @benhalpern I just a pull request icon as the logo in the nav bar.  I think it looks pretty good.  https://nrobinson2000.github.io/1pr/

**Pull request merged**
