### PR TITLE
adds a list of 1pr repo contributors to page

### PR DESCRIPTION
**Pull request by josephjguerra**
mini hall of fame on 1pr page for contributors approved for the day!

plenty of opportunities to expand this list to add images, links, and details for each contributor

### CODE REVIEW

**Comment by josephjguerra** [comment]
We certainly could do it with plain JS, instead of jQuery. Perhaps others will us jQuery for future PRs.... or are more comfortable with jQuery. I'll leave that to @benhalpern to yea 👍  or neh 👎

**Comment by aaroneiche** [comment]
FWIW, I'll throw my vote (as if I had one) behind this. I asked about jQuery because my first thought usually is to try and go as simplistic as possible. Again, I think including the contributors is a wonderful idea. 👍

**Comment by woubuc** [comment]
D'oh, I should have checked the open PR's before opening my own. I essentially implemented the same in #12 along with some css tweaks.

FWIW my implementation uses vanilla JS.

**Comment by aaroneiche** [comment]
You could probably merge your changes with @josephjguerra and submit as a PR, or branch of his and ask to merge in.

**Comment by woubuc** [comment]
Wouldn't that essentially replace all his changes? Or you mean use @josephjguerra's jQuery code and just add my css additions to it?

**Comment by aaroneiche** [comment]
@woubuc : Either way - Whatever you think makes the most valuable addition to the project.

**Comment by josephjguerra** [comment]
+1 to your PR @woubuc We're both doing the same thing, but you have some extra additions, and the pure JS version.

**Comment by woubuc** [comment]
@josephjguerra I've merged your changes into my PR, I kept my version of the script (cause it doesn't use jQuery) but this way seems fair since the commit history now shows that you came up with the contributors thingy first

**Comment by josephjguerra** [comment]
Nice, thanks @woubuc Kinda exciting to see if we'll be picked for the PR 😀

**Pull request merged**
