### PR TITLE
Added gitter sidecar and other changes

### PR DESCRIPTION
**Pull request by nrobinson2000**
@benhalpern has not created a gitter room for the project so the button will not work yet.

@dakebl I'm having some conflict with the css.  Is it possible to move the buttons in the footer to the left, out of the way of the gitter button?  Also, the text in the gitter button is unintentionally underlined.

https://nrobinson2000.github.io/1pr/

### CODE REVIEW

**Comment by dakebl** [comment]
@nrobinson2000 - You could wrap the buttons in a div with a class of footer-buttons.
Then you could style the class with a right-padding of 170px:

  ``.footer-buttons {
	padding-right: 170px;  
  }``

That'll give you this:
image

It might be worth considering moving them completely to left though. That can be achieved by simply removing ``justify-content: flex-end; `` from the footer styling
image

**Comment by woubuc** [comment]
> You could wrap the buttons in a div
If you do, make sure to add the `display:flex` to that div, cause flex only works on direct child elements.

But I agree with @dakebl, moving the buttons to the left may be the better option visually as well.

**Comment by nrobinson2000** [comment]
I moved the icons to the left, still trying to figure out how to remove the unintentional underlining of `OPEN CHAT` on the button.

**Comment by woubuc** [comment]
As with all the other underlines probably, something like
```
.gitter-open-chat-button::after, .gitter-open-chat-button:visited::after { display: none; }
```

Cause the underline isn't done with `text-decoration`, but rather it's an `::after` pseudo-element

**Comment by nrobinson2000** [comment]
That worked @woubuc

**Comment by nrobinson2000** [comment]
@benhalpern I think everyone would be okay with merging this pull request today.  Does anyone object?

**Comment by frattaro** [comment]
@nrobinson2000 if we had a voting feature, we wouldn't need to straw poll in PR comments, lol

**Comment by nrobinson2000** [comment]
@frattaro A voting system should be the next major feature.

**Comment by nrobinson2000** [comment]
@benhalpern All you need to do after merging this PR is enable travis ci and gitter for this project, and then everything will be all set.

**Comment by benhalpern** [comment]
I'm having trouble with gitter. I think there may be an issue where I first created a gitter community when thepracticaldev was a "user" account and then switched it to an org account. Either way, I'm not seeing a way to create https://gitter.im/thepracticaldev/1pr

Is there anything I'm missing?

**Comment by woubuc** [comment]
@nrobinson2000 I'm trying to check out your changes, but it seems that scripts/sidecar.js isn't a javascript file but rather a binary file or something? Could you look into that?

**Comment by nrobinson2000** [comment]
@woubuc I think so... I'm just using the embed code from https://sidecar.gitter.im/

**Comment by dakebl** [comment]
@woubuc I replaced the hosted gitter js (weird binary) with a local copy and updated the js on the index page

**Comment by nrobinson2000** [comment]
@dakebl So did I on this pull request

**Comment by dakebl** [comment]
@benhalpern try this: https://gitter.im/home/explore#createcommunity

**Comment by nrobinson2000** [comment]
@dakebl I removed the `target="_blank"` from the PR icon in the menubar to prevent opening a ton of tabs of the same page.

**Comment by dakebl** [comment]
I'd suggest closing this PR @nrobinson2000 as it was merged in with https://github.com/thepracticaldev/1pr/pull/30 😄

**Comment by nrobinson2000** [comment]
Okay I'll close it.  Has @benhalpern had any luck with gitter?

**Comment by dakebl** [comment]
He hasn't mentioned it and Gitter is still showing a 404, so I would guess that he hasn't so far.

**Pull request closed without merging**
